[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install .']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT' 